# upload.py
import os
import pickle
from google.auth.transport.requests import Request
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# YouTube API izinleri
SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

def authenticate_youtube():
    """OAuth2 token'ı yönetir (GitHub Actions uyumlu)."""
    creds = None
    token_path = "token.pickle"

    # Önceden kaydedilmiş token varsa yükle
    if os.path.exists(token_path):
        with open(token_path, "rb") as token:
            creds = pickle.load(token)

    # Geçersizse yenile veya yeni oluştur
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            # client_secret.json GitHub Secrets'ten decode edilmiş olmalı
            if not os.path.exists("client_secret.json"):
                raise FileNotFoundError("❌ client_secret.json bulunamadı (GitHub Secrets'ten decode edilmemiş)")
            flow = InstalledAppFlow.from_client_secrets_file("client_secret.json", SCOPES)
            # GitHub Actions'ta headless modda çalışır
            creds = flow.run_local_server(port=0, open_browser=False)
        # Token'ı kaydet
        with open(token_path, "wb") as token:
            pickle.dump(creds, token)

    return build("youtube", "v3", credentials=creds)

def upload_to_youtube(video_path: str, title: str) -> str:
    """
    Videoyu YouTube'a yükler.
    İlk çalıştırmada GitHub Actions log'unda URL çıkar → manuel onay gerekir.
    Sonraki çalıştırmalarda token.pickle sayesinde otomatik.
    """
    try:
        youtube = authenticate_youtube()

        # Başlık ve açıklama (İngilizce)
        safe_title = title[:95] + "..." if len(title) > 95 else title
        description = (
            "Automatically generated by Synapse Daily AI pipeline.\n"
            "From idea → script → voice → video → upload.\n"
            "Join us for daily AI insights!"
        )

        request_body = {
            "snippet": {
                "title": safe_title,
                "description": description,
                "tags": ["AI", "automation", "SynapseDaily", "artificial intelligence"],
                "categoryId": "28"  # Science & Technology
            },
            "status": {
                "privacyStatus": "private"  # Önce gizli, sonra sen public yaparsın
            }
        }

        media_file = MediaFileUpload(video_path, chunksize=-1, resumable=True)

        request = youtube.videos().insert(
            part="snippet,status",
            body=request_body,
            media_body=media_file
        )

        response = None
        while response is None:
            status, response = request.next_chunk()
            if status:
                print(f"📤 YouTube'a yükleme ilerlemesi: {int(status.progress() * 100)}%")

        video_id = response["id"]
        return f"✅ YouTube'a yüklendi!\nVideo ID: {video_id}\nBaşlık: {safe_title}"

    except Exception as e:
        return f"❌ YouTube yükleme HATASI:\n{str(e)}"